// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using P05Library.API.Models;

#nullable disable

namespace P05_2Library.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231220160622_CurrentState")]
    partial class CurrentState
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("P06Library.Shared.Auth.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("P06Library.Shared.Library.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(8,2)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Freida Simonis",
                            Barcode = "8",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Price = 679.119312429856m,
                            ReleaseDate = new DateTime(2023, 11, 21, 7, 27, 17, 435, DateTimeKind.Local).AddTicks(4277),
                            Title = "Gorgeous Wooden Chair"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Serenity Botsford",
                            Barcode = "6",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Price = 419.395071499234m,
                            ReleaseDate = new DateTime(2023, 4, 25, 21, 12, 29, 415, DateTimeKind.Local).AddTicks(1788),
                            Title = "Sleek Wooden Chicken"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Amalia Herman",
                            Barcode = "7",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Price = 276.019507477535m,
                            ReleaseDate = new DateTime(2023, 6, 20, 15, 59, 12, 595, DateTimeKind.Local).AddTicks(7050),
                            Title = "Rustic Soft Car"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Zachariah Johns",
                            Barcode = "7",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Price = 526.029559857226m,
                            ReleaseDate = new DateTime(2023, 12, 15, 9, 28, 53, 560, DateTimeKind.Local).AddTicks(3418),
                            Title = "Fantastic Concrete Chicken"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Garrett Braun",
                            Barcode = "0",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Price = 633.873313080926m,
                            ReleaseDate = new DateTime(2023, 2, 9, 2, 29, 21, 265, DateTimeKind.Local).AddTicks(8894),
                            Title = "Generic Rubber Chips"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Harold Cruickshank",
                            Barcode = "0",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Price = 887.110725245024m,
                            ReleaseDate = new DateTime(2023, 7, 22, 10, 48, 5, 81, DateTimeKind.Local).AddTicks(2307),
                            Title = "Generic Concrete Bike"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Kaylie Wehner",
                            Barcode = "4",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 212.662704598933m,
                            ReleaseDate = new DateTime(2023, 2, 7, 2, 1, 6, 924, DateTimeKind.Local).AddTicks(4139),
                            Title = "Ergonomic Plastic Computer"
                        },
                        new
                        {
                            Id = 8,
                            Author = "Florence O'Hara",
                            Barcode = "3",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Price = 476.020144769466m,
                            ReleaseDate = new DateTime(2023, 5, 25, 4, 26, 58, 388, DateTimeKind.Local).AddTicks(9623),
                            Title = "Licensed Concrete Bike"
                        },
                        new
                        {
                            Id = 9,
                            Author = "Wiley Gulgowski",
                            Barcode = "1",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Price = 905.322284099796m,
                            ReleaseDate = new DateTime(2023, 11, 23, 13, 25, 58, 857, DateTimeKind.Local).AddTicks(1367),
                            Title = "Gorgeous Fresh Shirt"
                        },
                        new
                        {
                            Id = 10,
                            Author = "Gabrielle Casper",
                            Barcode = "7",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Price = 60.7177984624718m,
                            ReleaseDate = new DateTime(2023, 5, 16, 7, 59, 40, 346, DateTimeKind.Local).AddTicks(4276),
                            Title = "Generic Steel Ball"
                        },
                        new
                        {
                            Id = 11,
                            Author = "Kianna Tromp",
                            Barcode = "7",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 854.154395135192m,
                            ReleaseDate = new DateTime(2023, 8, 26, 17, 17, 45, 903, DateTimeKind.Local).AddTicks(7445),
                            Title = "Small Frozen Car"
                        },
                        new
                        {
                            Id = 12,
                            Author = "Roel Crona",
                            Barcode = "6",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Price = 471.610621951339m,
                            ReleaseDate = new DateTime(2023, 1, 4, 8, 28, 34, 24, DateTimeKind.Local).AddTicks(9829),
                            Title = "Intelligent Steel Car"
                        },
                        new
                        {
                            Id = 13,
                            Author = "Unique Shanahan",
                            Barcode = "9",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Price = 415.80337236114m,
                            ReleaseDate = new DateTime(2023, 12, 5, 22, 34, 18, 371, DateTimeKind.Local).AddTicks(9785),
                            Title = "Fantastic Metal Keyboard"
                        },
                        new
                        {
                            Id = 14,
                            Author = "Virgil Waters",
                            Barcode = "0",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Price = 14.48730095778m,
                            ReleaseDate = new DateTime(2023, 10, 17, 23, 12, 38, 824, DateTimeKind.Local).AddTicks(5219),
                            Title = "Generic Wooden Cheese"
                        },
                        new
                        {
                            Id = 15,
                            Author = "Abelardo Hermann",
                            Barcode = "8",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Price = 16.8119918926675m,
                            ReleaseDate = new DateTime(2023, 7, 8, 13, 59, 39, 409, DateTimeKind.Local).AddTicks(7066),
                            Title = "Tasty Fresh Cheese"
                        },
                        new
                        {
                            Id = 16,
                            Author = "Imogene Cassin",
                            Barcode = "0",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Price = 612.278680905364m,
                            ReleaseDate = new DateTime(2023, 3, 22, 4, 39, 4, 681, DateTimeKind.Local).AddTicks(8907),
                            Title = "Fantastic Cotton Gloves"
                        },
                        new
                        {
                            Id = 17,
                            Author = "Freddy Kuvalis",
                            Barcode = "5",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Price = 878.871765064016m,
                            ReleaseDate = new DateTime(2022, 12, 22, 4, 14, 11, 834, DateTimeKind.Local).AddTicks(8303),
                            Title = "Unbranded Metal Hat"
                        },
                        new
                        {
                            Id = 18,
                            Author = "Camren Toy",
                            Barcode = "5",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Price = 940.814879371698m,
                            ReleaseDate = new DateTime(2023, 5, 26, 19, 31, 45, 675, DateTimeKind.Local).AddTicks(4533),
                            Title = "Unbranded Frozen Mouse"
                        },
                        new
                        {
                            Id = 19,
                            Author = "Ally Brekke",
                            Barcode = "4",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Price = 475.131881632904m,
                            ReleaseDate = new DateTime(2023, 6, 17, 4, 59, 24, 687, DateTimeKind.Local).AddTicks(5959),
                            Title = "Handcrafted Wooden Sausages"
                        },
                        new
                        {
                            Id = 20,
                            Author = "Alvis Waelchi",
                            Barcode = "1",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Price = 43.6775831215445m,
                            ReleaseDate = new DateTime(2023, 6, 29, 17, 4, 11, 758, DateTimeKind.Local).AddTicks(9646),
                            Title = "Ergonomic Metal Fish"
                        },
                        new
                        {
                            Id = 21,
                            Author = "Toby Feil",
                            Barcode = "9",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Price = 122.155600068698m,
                            ReleaseDate = new DateTime(2023, 5, 29, 13, 19, 12, 208, DateTimeKind.Local).AddTicks(438),
                            Title = "Incredible Fresh Soap"
                        },
                        new
                        {
                            Id = 22,
                            Author = "Emery Reichert",
                            Barcode = "8",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Price = 810.480351352356m,
                            ReleaseDate = new DateTime(2023, 10, 18, 7, 27, 31, 204, DateTimeKind.Local).AddTicks(2443),
                            Title = "Gorgeous Soft Tuna"
                        },
                        new
                        {
                            Id = 23,
                            Author = "Hershel Torphy",
                            Barcode = "8",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Price = 208.202475922742m,
                            ReleaseDate = new DateTime(2023, 6, 17, 14, 6, 24, 992, DateTimeKind.Local).AddTicks(4045),
                            Title = "Gorgeous Wooden Table"
                        },
                        new
                        {
                            Id = 24,
                            Author = "Flo Paucek",
                            Barcode = "4",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Price = 430.155933462156m,
                            ReleaseDate = new DateTime(2023, 6, 28, 23, 32, 25, 165, DateTimeKind.Local).AddTicks(2141),
                            Title = "Small Metal Tuna"
                        },
                        new
                        {
                            Id = 25,
                            Author = "Zion Reichert",
                            Barcode = "7",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Price = 743.837137221749m,
                            ReleaseDate = new DateTime(2023, 12, 18, 21, 57, 23, 963, DateTimeKind.Local).AddTicks(5487),
                            Title = "Generic Soft Cheese"
                        },
                        new
                        {
                            Id = 26,
                            Author = "Judy Hartmann",
                            Barcode = "0",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Price = 635.754752597657m,
                            ReleaseDate = new DateTime(2023, 1, 16, 7, 31, 33, 28, DateTimeKind.Local).AddTicks(1325),
                            Title = "Ergonomic Rubber Chicken"
                        },
                        new
                        {
                            Id = 27,
                            Author = "Liana Ferry",
                            Barcode = "4",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Price = 663.536718269594m,
                            ReleaseDate = new DateTime(2022, 12, 30, 9, 49, 28, 685, DateTimeKind.Local).AddTicks(2832),
                            Title = "Awesome Plastic Chicken"
                        },
                        new
                        {
                            Id = 28,
                            Author = "Maymie Kuhn",
                            Barcode = "7",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Price = 289.121948837359m,
                            ReleaseDate = new DateTime(2023, 10, 30, 4, 3, 6, 153, DateTimeKind.Local).AddTicks(3428),
                            Title = "Handcrafted Concrete Tuna"
                        },
                        new
                        {
                            Id = 29,
                            Author = "Katarina Larson",
                            Barcode = "8",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Price = 129.940595376278m,
                            ReleaseDate = new DateTime(2023, 10, 18, 6, 32, 58, 43, DateTimeKind.Local).AddTicks(5835),
                            Title = "Handmade Plastic Bike"
                        },
                        new
                        {
                            Id = 30,
                            Author = "Yasmin Wisozk",
                            Barcode = "7",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Price = 185.643613699658m,
                            ReleaseDate = new DateTime(2023, 4, 23, 1, 15, 27, 51, DateTimeKind.Local).AddTicks(8025),
                            Title = "Gorgeous Wooden Pants"
                        },
                        new
                        {
                            Id = 31,
                            Author = "Lempi Moen",
                            Barcode = "2",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Price = 579.21628712314m,
                            ReleaseDate = new DateTime(2023, 3, 5, 17, 0, 39, 920, DateTimeKind.Local).AddTicks(1588),
                            Title = "Awesome Granite Hat"
                        },
                        new
                        {
                            Id = 32,
                            Author = "Nikolas Quitzon",
                            Barcode = "3",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Price = 383.278243241961m,
                            ReleaseDate = new DateTime(2023, 1, 9, 4, 30, 10, 284, DateTimeKind.Local).AddTicks(8825),
                            Title = "Unbranded Fresh Table"
                        },
                        new
                        {
                            Id = 33,
                            Author = "Raoul Kerluke",
                            Barcode = "5",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Price = 896.730729824272m,
                            ReleaseDate = new DateTime(2023, 8, 4, 23, 51, 32, 818, DateTimeKind.Local).AddTicks(2816),
                            Title = "Refined Wooden Computer"
                        },
                        new
                        {
                            Id = 34,
                            Author = "Manuela Torp",
                            Barcode = "3",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 324.517499184477m,
                            ReleaseDate = new DateTime(2023, 6, 7, 22, 27, 54, 198, DateTimeKind.Local).AddTicks(7922),
                            Title = "Incredible Cotton Gloves"
                        },
                        new
                        {
                            Id = 35,
                            Author = "Reese Lang",
                            Barcode = "8",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Price = 929.139840084659m,
                            ReleaseDate = new DateTime(2023, 2, 19, 8, 39, 37, 193, DateTimeKind.Local).AddTicks(7784),
                            Title = "Rustic Fresh Bacon"
                        },
                        new
                        {
                            Id = 36,
                            Author = "Kiel Mills",
                            Barcode = "2",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 158.364214679396m,
                            ReleaseDate = new DateTime(2023, 8, 8, 15, 13, 13, 336, DateTimeKind.Local).AddTicks(8723),
                            Title = "Small Rubber Pants"
                        },
                        new
                        {
                            Id = 37,
                            Author = "Laila Harber",
                            Barcode = "2",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Price = 218.78718086229m,
                            ReleaseDate = new DateTime(2023, 8, 8, 21, 3, 29, 894, DateTimeKind.Local).AddTicks(9883),
                            Title = "Awesome Soft Fish"
                        },
                        new
                        {
                            Id = 38,
                            Author = "Ramona Willms",
                            Barcode = "2",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Price = 245.410820124396m,
                            ReleaseDate = new DateTime(2023, 7, 19, 14, 48, 4, 822, DateTimeKind.Local).AddTicks(6294),
                            Title = "Generic Wooden Sausages"
                        },
                        new
                        {
                            Id = 39,
                            Author = "Ahmad Waelchi",
                            Barcode = "7",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 628.755980696416m,
                            ReleaseDate = new DateTime(2023, 1, 2, 8, 47, 11, 776, DateTimeKind.Local).AddTicks(3598),
                            Title = "Handmade Steel Salad"
                        },
                        new
                        {
                            Id = 40,
                            Author = "Ottilie Larson",
                            Barcode = "7",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Price = 890.001594146714m,
                            ReleaseDate = new DateTime(2023, 8, 16, 21, 18, 4, 102, DateTimeKind.Local).AddTicks(6469),
                            Title = "Licensed Frozen Car"
                        },
                        new
                        {
                            Id = 41,
                            Author = "Christiana Hagenes",
                            Barcode = "7",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 501.19964468535m,
                            ReleaseDate = new DateTime(2023, 10, 8, 0, 15, 38, 729, DateTimeKind.Local).AddTicks(8765),
                            Title = "Handcrafted Cotton Tuna"
                        },
                        new
                        {
                            Id = 42,
                            Author = "Leanna Swift",
                            Barcode = "2",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 474.158561197649m,
                            ReleaseDate = new DateTime(2023, 1, 26, 16, 26, 12, 992, DateTimeKind.Local).AddTicks(5983),
                            Title = "Awesome Granite Fish"
                        },
                        new
                        {
                            Id = 43,
                            Author = "Gerard Satterfield",
                            Barcode = "1",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Price = 309.665064914462m,
                            ReleaseDate = new DateTime(2023, 10, 11, 17, 47, 24, 699, DateTimeKind.Local).AddTicks(1904),
                            Title = "Handmade Rubber Gloves"
                        },
                        new
                        {
                            Id = 44,
                            Author = "Maybell Orn",
                            Barcode = "2",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Price = 823.62140813592m,
                            ReleaseDate = new DateTime(2023, 11, 30, 7, 2, 16, 405, DateTimeKind.Local).AddTicks(74),
                            Title = "Incredible Granite Gloves"
                        },
                        new
                        {
                            Id = 45,
                            Author = "Erwin Koelpin",
                            Barcode = "6",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Price = 717.609017980569m,
                            ReleaseDate = new DateTime(2023, 10, 9, 9, 27, 42, 768, DateTimeKind.Local).AddTicks(8265),
                            Title = "Practical Rubber Gloves"
                        },
                        new
                        {
                            Id = 46,
                            Author = "Stewart Harber",
                            Barcode = "3",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 242.468765747952m,
                            ReleaseDate = new DateTime(2023, 5, 4, 2, 52, 52, 53, DateTimeKind.Local).AddTicks(4634),
                            Title = "Unbranded Soft Fish"
                        },
                        new
                        {
                            Id = 47,
                            Author = "Skye Metz",
                            Barcode = "7",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Price = 3.31604853054325m,
                            ReleaseDate = new DateTime(2023, 2, 9, 7, 10, 59, 536, DateTimeKind.Local).AddTicks(2758),
                            Title = "Rustic Granite Pants"
                        },
                        new
                        {
                            Id = 48,
                            Author = "Malachi Collins",
                            Barcode = "6",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Price = 306.351716509718m,
                            ReleaseDate = new DateTime(2023, 11, 13, 0, 2, 26, 743, DateTimeKind.Local).AddTicks(9697),
                            Title = "Awesome Metal Keyboard"
                        },
                        new
                        {
                            Id = 49,
                            Author = "Waino Christiansen",
                            Barcode = "6",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Price = 756.842380142232m,
                            ReleaseDate = new DateTime(2023, 9, 8, 13, 17, 16, 272, DateTimeKind.Local).AddTicks(3708),
                            Title = "Ergonomic Wooden Bacon"
                        },
                        new
                        {
                            Id = 50,
                            Author = "Carroll Daniel",
                            Barcode = "5",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Price = 533.598870003875m,
                            ReleaseDate = new DateTime(2023, 3, 28, 9, 41, 50, 304, DateTimeKind.Local).AddTicks(5786),
                            Title = "Rustic Wooden Bacon"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
