// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using P05Library.API.Models;

#nullable disable

namespace P05_2Library.API.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("P06Library.Shared.Auth.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("P06Library.Shared.Library.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(8,2)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Freida Simonis",
                            Barcode = "8",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Price = 679.119312429856m,
                            ReleaseDate = new DateTime(2023, 10, 30, 0, 46, 29, 266, DateTimeKind.Local).AddTicks(9622),
                            Title = "Gorgeous Wooden Chair"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Serenity Botsford",
                            Barcode = "6",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Price = 419.395071499234m,
                            ReleaseDate = new DateTime(2023, 4, 3, 14, 31, 41, 246, DateTimeKind.Local).AddTicks(7658),
                            Title = "Sleek Wooden Chicken"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Amalia Herman",
                            Barcode = "7",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Price = 276.019507477535m,
                            ReleaseDate = new DateTime(2023, 5, 29, 9, 18, 24, 427, DateTimeKind.Local).AddTicks(2956),
                            Title = "Rustic Soft Car"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Zachariah Johns",
                            Barcode = "7",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Price = 526.029559857226m,
                            ReleaseDate = new DateTime(2023, 11, 23, 2, 48, 5, 391, DateTimeKind.Local).AddTicks(9416),
                            Title = "Fantastic Concrete Chicken"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Garrett Braun",
                            Barcode = "0",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Price = 633.873313080926m,
                            ReleaseDate = new DateTime(2023, 1, 17, 19, 48, 33, 97, DateTimeKind.Local).AddTicks(4913),
                            Title = "Generic Rubber Chips"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Harold Cruickshank",
                            Barcode = "0",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Price = 887.110725245024m,
                            ReleaseDate = new DateTime(2023, 6, 30, 4, 7, 16, 912, DateTimeKind.Local).AddTicks(8321),
                            Title = "Generic Concrete Bike"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Kaylie Wehner",
                            Barcode = "4",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 212.662704598933m,
                            ReleaseDate = new DateTime(2023, 1, 15, 19, 20, 18, 756, DateTimeKind.Local).AddTicks(166),
                            Title = "Ergonomic Plastic Computer"
                        },
                        new
                        {
                            Id = 8,
                            Author = "Florence O'Hara",
                            Barcode = "3",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Price = 476.020144769466m,
                            ReleaseDate = new DateTime(2023, 5, 2, 21, 46, 10, 220, DateTimeKind.Local).AddTicks(5666),
                            Title = "Licensed Concrete Bike"
                        },
                        new
                        {
                            Id = 9,
                            Author = "Wiley Gulgowski",
                            Barcode = "1",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Price = 905.322284099796m,
                            ReleaseDate = new DateTime(2023, 11, 1, 6, 45, 10, 688, DateTimeKind.Local).AddTicks(7426),
                            Title = "Gorgeous Fresh Shirt"
                        },
                        new
                        {
                            Id = 10,
                            Author = "Gabrielle Casper",
                            Barcode = "7",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Price = 60.7177984624718m,
                            ReleaseDate = new DateTime(2023, 4, 24, 1, 18, 52, 178, DateTimeKind.Local).AddTicks(400),
                            Title = "Generic Steel Ball"
                        },
                        new
                        {
                            Id = 11,
                            Author = "Kianna Tromp",
                            Barcode = "7",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 854.154395135192m,
                            ReleaseDate = new DateTime(2023, 8, 4, 10, 36, 57, 735, DateTimeKind.Local).AddTicks(3589),
                            Title = "Small Frozen Car"
                        },
                        new
                        {
                            Id = 12,
                            Author = "Roel Crona",
                            Barcode = "6",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Price = 471.610621951339m,
                            ReleaseDate = new DateTime(2022, 12, 13, 1, 47, 45, 856, DateTimeKind.Local).AddTicks(5969),
                            Title = "Intelligent Steel Car"
                        },
                        new
                        {
                            Id = 13,
                            Author = "Unique Shanahan",
                            Barcode = "9",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Price = 415.80337236114m,
                            ReleaseDate = new DateTime(2023, 11, 13, 15, 53, 30, 203, DateTimeKind.Local).AddTicks(5941),
                            Title = "Fantastic Metal Keyboard"
                        },
                        new
                        {
                            Id = 14,
                            Author = "Virgil Waters",
                            Barcode = "0",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Price = 14.48730095778m,
                            ReleaseDate = new DateTime(2023, 9, 25, 16, 31, 50, 656, DateTimeKind.Local).AddTicks(1391),
                            Title = "Generic Wooden Cheese"
                        },
                        new
                        {
                            Id = 15,
                            Author = "Abelardo Hermann",
                            Barcode = "8",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Price = 16.8119918926675m,
                            ReleaseDate = new DateTime(2023, 6, 16, 7, 18, 51, 241, DateTimeKind.Local).AddTicks(3278),
                            Title = "Tasty Fresh Cheese"
                        },
                        new
                        {
                            Id = 16,
                            Author = "Imogene Cassin",
                            Barcode = "0",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Price = 612.278680905364m,
                            ReleaseDate = new DateTime(2023, 2, 27, 21, 58, 16, 513, DateTimeKind.Local).AddTicks(5141),
                            Title = "Fantastic Cotton Gloves"
                        },
                        new
                        {
                            Id = 17,
                            Author = "Freddy Kuvalis",
                            Barcode = "5",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Price = 878.871765064016m,
                            ReleaseDate = new DateTime(2022, 11, 29, 21, 33, 23, 666, DateTimeKind.Local).AddTicks(4557),
                            Title = "Unbranded Metal Hat"
                        },
                        new
                        {
                            Id = 18,
                            Author = "Camren Toy",
                            Barcode = "5",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Price = 940.814879371698m,
                            ReleaseDate = new DateTime(2023, 5, 4, 12, 50, 57, 507, DateTimeKind.Local).AddTicks(785),
                            Title = "Unbranded Frozen Mouse"
                        },
                        new
                        {
                            Id = 19,
                            Author = "Ally Brekke",
                            Barcode = "4",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Price = 475.131881632904m,
                            ReleaseDate = new DateTime(2023, 5, 25, 22, 18, 36, 519, DateTimeKind.Local).AddTicks(2228),
                            Title = "Handcrafted Wooden Sausages"
                        },
                        new
                        {
                            Id = 20,
                            Author = "Alvis Waelchi",
                            Barcode = "1",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Price = 43.6775831215445m,
                            ReleaseDate = new DateTime(2023, 6, 7, 10, 23, 23, 590, DateTimeKind.Local).AddTicks(5932),
                            Title = "Ergonomic Metal Fish"
                        },
                        new
                        {
                            Id = 21,
                            Author = "Toby Feil",
                            Barcode = "9",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Price = 122.155600068698m,
                            ReleaseDate = new DateTime(2023, 5, 7, 6, 38, 24, 39, DateTimeKind.Local).AddTicks(6740),
                            Title = "Incredible Fresh Soap"
                        },
                        new
                        {
                            Id = 22,
                            Author = "Emery Reichert",
                            Barcode = "8",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Price = 810.480351352356m,
                            ReleaseDate = new DateTime(2023, 9, 26, 0, 46, 43, 35, DateTimeKind.Local).AddTicks(8788),
                            Title = "Gorgeous Soft Tuna"
                        },
                        new
                        {
                            Id = 23,
                            Author = "Hershel Torphy",
                            Barcode = "8",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Price = 208.202475922742m,
                            ReleaseDate = new DateTime(2023, 5, 26, 7, 25, 36, 824, DateTimeKind.Local).AddTicks(405),
                            Title = "Gorgeous Wooden Table"
                        },
                        new
                        {
                            Id = 24,
                            Author = "Flo Paucek",
                            Barcode = "4",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Price = 430.155933462156m,
                            ReleaseDate = new DateTime(2023, 6, 6, 16, 51, 36, 996, DateTimeKind.Local).AddTicks(8498),
                            Title = "Small Metal Tuna"
                        },
                        new
                        {
                            Id = 25,
                            Author = "Zion Reichert",
                            Barcode = "7",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Price = 743.837137221749m,
                            ReleaseDate = new DateTime(2023, 11, 26, 15, 16, 35, 795, DateTimeKind.Local).AddTicks(1861),
                            Title = "Generic Soft Cheese"
                        },
                        new
                        {
                            Id = 26,
                            Author = "Judy Hartmann",
                            Barcode = "0",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Price = 635.754752597657m,
                            ReleaseDate = new DateTime(2022, 12, 25, 0, 50, 44, 859, DateTimeKind.Local).AddTicks(7713),
                            Title = "Ergonomic Rubber Chicken"
                        },
                        new
                        {
                            Id = 27,
                            Author = "Liana Ferry",
                            Barcode = "4",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Price = 663.536718269594m,
                            ReleaseDate = new DateTime(2022, 12, 8, 3, 8, 40, 516, DateTimeKind.Local).AddTicks(9238),
                            Title = "Awesome Plastic Chicken"
                        },
                        new
                        {
                            Id = 28,
                            Author = "Maymie Kuhn",
                            Barcode = "7",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Price = 289.121948837359m,
                            ReleaseDate = new DateTime(2023, 10, 7, 21, 22, 17, 984, DateTimeKind.Local).AddTicks(9884),
                            Title = "Handcrafted Concrete Tuna"
                        },
                        new
                        {
                            Id = 29,
                            Author = "Katarina Larson",
                            Barcode = "8",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Price = 129.940595376278m,
                            ReleaseDate = new DateTime(2023, 9, 25, 23, 52, 9, 875, DateTimeKind.Local).AddTicks(2311),
                            Title = "Handmade Plastic Bike"
                        },
                        new
                        {
                            Id = 30,
                            Author = "Yasmin Wisozk",
                            Barcode = "7",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Price = 185.643613699658m,
                            ReleaseDate = new DateTime(2023, 3, 31, 18, 34, 38, 883, DateTimeKind.Local).AddTicks(4486),
                            Title = "Gorgeous Wooden Pants"
                        },
                        new
                        {
                            Id = 31,
                            Author = "Lempi Moen",
                            Barcode = "2",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Price = 579.21628712314m,
                            ReleaseDate = new DateTime(2023, 2, 11, 10, 19, 51, 751, DateTimeKind.Local).AddTicks(8065),
                            Title = "Awesome Granite Hat"
                        },
                        new
                        {
                            Id = 32,
                            Author = "Nikolas Quitzon",
                            Barcode = "3",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Price = 383.278243241961m,
                            ReleaseDate = new DateTime(2022, 12, 17, 21, 49, 22, 116, DateTimeKind.Local).AddTicks(5321),
                            Title = "Unbranded Fresh Table"
                        },
                        new
                        {
                            Id = 33,
                            Author = "Raoul Kerluke",
                            Barcode = "5",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Price = 896.730729824272m,
                            ReleaseDate = new DateTime(2023, 7, 13, 17, 10, 44, 649, DateTimeKind.Local).AddTicks(9332),
                            Title = "Refined Wooden Computer"
                        },
                        new
                        {
                            Id = 34,
                            Author = "Manuela Torp",
                            Barcode = "3",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 324.517499184477m,
                            ReleaseDate = new DateTime(2023, 5, 16, 15, 47, 6, 30, DateTimeKind.Local).AddTicks(4484),
                            Title = "Incredible Cotton Gloves"
                        },
                        new
                        {
                            Id = 35,
                            Author = "Reese Lang",
                            Barcode = "8",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Price = 929.139840084659m,
                            ReleaseDate = new DateTime(2023, 1, 28, 1, 58, 49, 25, DateTimeKind.Local).AddTicks(4368),
                            Title = "Rustic Fresh Bacon"
                        },
                        new
                        {
                            Id = 36,
                            Author = "Kiel Mills",
                            Barcode = "2",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 158.364214679396m,
                            ReleaseDate = new DateTime(2023, 7, 17, 8, 32, 25, 168, DateTimeKind.Local).AddTicks(5297),
                            Title = "Small Rubber Pants"
                        },
                        new
                        {
                            Id = 37,
                            Author = "Laila Harber",
                            Barcode = "2",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Price = 218.78718086229m,
                            ReleaseDate = new DateTime(2023, 7, 17, 14, 22, 41, 726, DateTimeKind.Local).AddTicks(6473),
                            Title = "Awesome Soft Fish"
                        },
                        new
                        {
                            Id = 38,
                            Author = "Ramona Willms",
                            Barcode = "2",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Price = 245.410820124396m,
                            ReleaseDate = new DateTime(2023, 6, 27, 8, 7, 16, 654, DateTimeKind.Local).AddTicks(2900),
                            Title = "Generic Wooden Sausages"
                        },
                        new
                        {
                            Id = 39,
                            Author = "Ahmad Waelchi",
                            Barcode = "7",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 628.755980696416m,
                            ReleaseDate = new DateTime(2022, 12, 11, 2, 6, 23, 608, DateTimeKind.Local).AddTicks(220),
                            Title = "Handmade Steel Salad"
                        },
                        new
                        {
                            Id = 40,
                            Author = "Ottilie Larson",
                            Barcode = "7",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Price = 890.001594146714m,
                            ReleaseDate = new DateTime(2023, 7, 25, 14, 37, 15, 934, DateTimeKind.Local).AddTicks(3135),
                            Title = "Licensed Frozen Car"
                        },
                        new
                        {
                            Id = 41,
                            Author = "Christiana Hagenes",
                            Barcode = "7",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 501.19964468535m,
                            ReleaseDate = new DateTime(2023, 9, 15, 17, 34, 50, 561, DateTimeKind.Local).AddTicks(5450),
                            Title = "Handcrafted Cotton Tuna"
                        },
                        new
                        {
                            Id = 42,
                            Author = "Leanna Swift",
                            Barcode = "2",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 474.158561197649m,
                            ReleaseDate = new DateTime(2023, 1, 4, 9, 45, 24, 824, DateTimeKind.Local).AddTicks(2665),
                            Title = "Awesome Granite Fish"
                        },
                        new
                        {
                            Id = 43,
                            Author = "Gerard Satterfield",
                            Barcode = "1",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Price = 309.665064914462m,
                            ReleaseDate = new DateTime(2023, 9, 19, 11, 6, 36, 530, DateTimeKind.Local).AddTicks(8601),
                            Title = "Handmade Rubber Gloves"
                        },
                        new
                        {
                            Id = 44,
                            Author = "Maybell Orn",
                            Barcode = "2",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Price = 823.62140813592m,
                            ReleaseDate = new DateTime(2023, 11, 8, 0, 21, 28, 236, DateTimeKind.Local).AddTicks(6783),
                            Title = "Incredible Granite Gloves"
                        },
                        new
                        {
                            Id = 45,
                            Author = "Erwin Koelpin",
                            Barcode = "6",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Price = 717.609017980569m,
                            ReleaseDate = new DateTime(2023, 9, 17, 2, 46, 54, 600, DateTimeKind.Local).AddTicks(4993),
                            Title = "Practical Rubber Gloves"
                        },
                        new
                        {
                            Id = 46,
                            Author = "Stewart Harber",
                            Barcode = "3",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 242.468765747952m,
                            ReleaseDate = new DateTime(2023, 4, 11, 20, 12, 3, 885, DateTimeKind.Local).AddTicks(1404),
                            Title = "Unbranded Soft Fish"
                        },
                        new
                        {
                            Id = 47,
                            Author = "Skye Metz",
                            Barcode = "7",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Price = 3.31604853054325m,
                            ReleaseDate = new DateTime(2023, 1, 18, 0, 30, 11, 367, DateTimeKind.Local).AddTicks(9547),
                            Title = "Rustic Granite Pants"
                        },
                        new
                        {
                            Id = 48,
                            Author = "Malachi Collins",
                            Barcode = "6",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Price = 306.351716509718m,
                            ReleaseDate = new DateTime(2023, 10, 21, 17, 21, 38, 575, DateTimeKind.Local).AddTicks(6504),
                            Title = "Awesome Metal Keyboard"
                        },
                        new
                        {
                            Id = 49,
                            Author = "Waino Christiansen",
                            Barcode = "6",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Price = 756.842380142232m,
                            ReleaseDate = new DateTime(2023, 8, 17, 6, 36, 28, 104, DateTimeKind.Local).AddTicks(601),
                            Title = "Ergonomic Wooden Bacon"
                        },
                        new
                        {
                            Id = 50,
                            Author = "Carroll Daniel",
                            Barcode = "5",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Price = 533.598870003875m,
                            ReleaseDate = new DateTime(2023, 3, 6, 3, 1, 2, 136, DateTimeKind.Local).AddTicks(2701),
                            Title = "Rustic Wooden Bacon"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
